name=Adafruit DVI Audio
version=0.0.1
author=Adafruit
maintainer=Adafruit <info@adafruit.com>
sentence=DVI video plus digital audio on RP2350 HSTX.
paragraph=Thin wrapper around fliperama86/pico_hdmi.
category=Display
url=https://github.com/adafruit/Adafruit_DVI_Audio
architectures=rp2040
depends=Adafruit GFX Library
